# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zReuCfFTvidteAdI-FIGlBFETNH6rL1h
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('/content/diabetes.csv')

# Show first 5 rows
df.head()

# Dataset shape
print("Shape of dataset:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Dataset info
print("\nDataset Info:")
print(df.info())

# Missing values
df.isnull().sum()

# Statistical summary
df.describe()

sns.countplot(x='Outcome', data=df)

plt.title("Diabetes Outcome Count")
plt.xlabel("Outcome")
plt.ylabel("Count")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Glucose'], bins=20)

plt.title("Glucose Distribution")
plt.xlabel("Glucose")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['Age'], bins=20)

plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

"""## Key Insights

1. Glucose level has the strongest relationship with diabetes outcome.
2. Patients with higher BMI are more likely to have diabetes.
3. Age also contributes to diabetes occurrence.
4. Correlation analysis helped identify important features.

## Conclusion

This analysis explored the diabetes dataset using Python, Pandas, Matplotlib, and Seaborn. The analysis showed that glucose and BMI are important indicators of diabetes.
"""